Main svc
Olhha/java-explore-with-me pull request #4
Opened 2023-08-09 08:18 UTC by Olhha

- added Main Service

2023-08-09 21:24 UTC, AnastasiyaFomkina requested changes
Очень клевая работа получилась, молодец 🔥

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/categories/CategoryAdminController.java
> +    public CategoryAdminController(CategoryService categoryService) {
Чтобы максимально избавится от однотипного кода, очень удобно использовать [@RequiredArgsConstructor ](https://www.baeldung.com/spring-injection-lombok#:~:text=Constructor%20Injection%20With%20Lombok) из библиотеки `lombok`. Он автоматически заинжектит все нужные нам поля

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/categories/model/Category.java
> +    Long id;
Не хватает модификатора доступа

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/compilations/CompilationRepository.java
> +    Page<Compilation> findAllPinned(@Param("pinned") Boolean pinned, Pageable page);
Нужно возвращать список, так как при `Pageable` запросе `SpringData` будет возвращать список с определенным количеством элементов. 
Объект `Page` нам не нужен, так как мы его никак не используем, кроме как кастуем обратно к списку

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/compilations/CompilationService.java
> +        if (updateCompRequest.getPinned() != null)
Обновление полей нужно вынести в маппер здесь и во всех других сервисах, где есть обновление сущности

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/events/EventRepository.java
> +    Page<Event> findByInitiatorIdOrderByCreatedDesc(Long initiator, Pageable pageable);
Здесь тоже лучше сразу список возвращать

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/resources/schema.sql
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/events/model/EventStateAdminAction.java
> +public enum EventStateAdminAction {
Похоже на то, что нигде не используется

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/events/model/EventStateOwnerAction.java
> +public enum EventStateOwnerAction {
И это перечисление тоже

2023-08-09 21:24 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/events/EventService.java
> +    private static EventStatus parseAdminStateActionOrThrow(String stateAction) {
Здесь и методе ниже лучше использовать перечисления, которые сейчас не используются, а не строку.
Если добавить в перечисление параметры,
тогда можно будет написать метод, который будет возвращать корректный `EventStatus `, основываясь на переданном `StateAction`.
Соответственно не придется всегда актуализировать данный метод, если вдруг добавится новое условие.
[Здесь](https://www.baeldung.com/java-enum-values) можно почитать про то, как добавлять и использовать параметры в enum

2023-08-09 23:28 UTC, Olhha commented on main-service/src/main/java/ru/practicum/categories/CategoryAdminController.java
> +    public CategoryAdminController(CategoryService categoryService) {
done

2023-08-09 23:29 UTC, Olhha commented on main-service/src/main/java/ru/practicum/categories/model/Category.java
> +    Long id;
done

2023-08-09 23:30 UTC, Olhha commented on main-service/src/main/java/ru/practicum/compilations/CompilationRepository.java
> +    Page<Compilation> findAllPinned(@Param("pinned") Boolean pinned, Pageable page);
done

2023-08-09 23:32 UTC, Olhha commented on main-service/src/main/java/ru/practicum/events/EventRepository.java
> +    Page<Event> findByInitiatorIdOrderByCreatedDesc(Long initiator, Pageable pageable);
done

2023-08-10 18:15 UTC, Olhha commented on main-service/src/main/java/ru/practicum/events/EventService.java
> +    private static EventStatus parseAdminStateActionOrThrow(String stateAction) {
переделала, но не очень уверена, что сделала всё правильно 🤪

2023-08-10 18:15 UTC, Olhha commented on main-service/src/main/java/ru/practicum/events/model/EventStateOwnerAction.java
> +public enum EventStateOwnerAction {
done

2023-08-10 18:15 UTC, Olhha commented on main-service/src/main/java/ru/practicum/events/model/EventStateAdminAction.java
> +public enum EventStateAdminAction {
done

2023-08-11 17:50 UTC, Olhha commented on main-service/src/main/resources/schema.sql
Добавила индексы в табличку статистики, потому что к ней очень часто идёт обращение.
А в main_service не могу определиться стоит ли добавлять ещё индексы?
я вижу в базе Postgres автоматом создал индексы на Primary поля и Unique constraint-ы. 
По идее, самая большая и часто запрашиваемая табличка это events, там пользователь и админ могут искать события по разным фильтрам, и в запросе может быть разная комбинация полей, а всего полей в фильтре штук 8, стоит ли делать индексы на все поля? я боюсь, что получу обратный эффект-снижение производительности при поиске и замедление вставки/изменения, из-за обновлении индексов

2023-08-12 19:53 UTC, AnastasiyaFomkina commented on main-service/src/main/resources/schema.sql
Да, в основном нужны только на статистику

2023-08-12 20:03 UTC, AnastasiyaFomkina approved these changes

2023-08-12 20:49 UTC, merged