Feature comments
Olhha/java-explore-with-me pull request #5
Opened 2023-08-12 21:24 UTC by Olhha

- добавлены Комментарии 
+ Postman тесты

2023-08-13 15:32 UTC, AnastasiyaFomkina requested changes
Получилась отличная фича, молодец 👍

2023-08-13 15:32 UTC, AnastasiyaFomkina commented on README.md
Распиши, пожалуйста, README более подробно:
* описание проекта
* основные endpoint'ы
* описание доп фичи

2023-08-15 11:44 UTC, Olhha commented on README.md
done

2023-08-15 20:16 UTC, AnastasiyaFomkina approved these changes

2023-08-15 20:27 UTC, merged